# Generated by Django 2.1.5 on 2019-02-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    operations = [
        migrations.CreateModel(
            name='net',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('body', models.CharField(max_length=300)),
                ('id_child', models.IntegerField()),
                ],
            ),
    ]
