# Generated by Django 2.1.1 on 2018-12-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='note_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('body', models.CharField(max_length=300)),
                ('pub_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
